### PR TITLE
Rebuilt against CDK 1.4.0

### PR DESCRIPTION
**Pull request by juhamust**
Fixes the compatibility issue with 1.4.0

### CODE REVIEW

**Comment by kennu** [comment]
Thanks!

**Comment by kennu** [comment]
I'm not sure how to best manage this kind of dependency, where this component basically needs to be rebuilt every time a new AWS CDK is released. I guess it should be done automatically.

**Comment by kennu** [comment]
For now, I published this as the latest version (0.9.6).

**Comment by juhamust** [comment]
At least this time the re-building was required: Bind method response was changed and rebuilding fixed. Perhaps things will settle as CDK gets more stable.

**Pull request merged**
